### ISSUE TITLE
Understanding SARIMAX prediction in _next_observation

### ISSUE THREAD

**Issue by ktattan** [notadamking/Bitcoin-Trader-RL#11]
First, thanks for making your code open source and for the great medium article. This is really great stuff.

I'm just going through your code and trying to understand it. In your [BitcoinTradingEnv.py script, under the `_next_observation` method](https://github.com/notadamking/Bitcoin-Trader-RL/blob/e5b83b1571f9fcfa6a67a2a810222f1f1751996c/env/BitcoinTradingEnv.py#L78), you have 

`past_df = self.stationary_df['Close'][:self.current_step + self.forecast_len + 1]`
 `forecast_model = SARIMAX(past_df.values, enforce_stationarity=False)`

If I understand this correctly, you are indexing all your close price data up to `current_step + forecast_len + 1` and then training the SARIMAX model on this data. But doesn't that mean you're looking ahead (into the future) by `forecast_len` days? I would have thought that you can only use data that is available up to the current time step, because we don't know the data from the future. So something like

`past_df = self.stationary_df['Close'][:self.current_step + 1]`
`forecast_model = SARIMAX(past_df.values, enforce_stationarity=False)`

Apologies if I am missing something obvious here.

**Comment by notadamking** [comment]
Hi @ktattan, thanks for reading the article and reaching out. You are not missing anything _obvious_, though you are missing an important detail of this environment, likely due to poor naming on my part.
If you look at the `_current_price` method, you will notice that the current price at any moment is actually the price at the `self.current_step + self.forecast_len`'th time step:

```python
def _current_price(self):
        return self.df['Close'].values[self.current_step + self.forecast_len] + 0.01
```

So essentially, we are just starting the environment `self.forecast_len` time steps into the initial data frame, because the SARIMAX algorithm requires at least as many input data points as it is going to predict. Does this make sense?

**Comment by ktattan** [comment]
Aah, that makes perfect sense. I didn't know that SARIMAX needed as many training points as it was going to predict. Thanks again @notadamking
